version: "3"
services:
  api:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "3030:3030"
    stdin_open: true
    tty: true
  mongo:
    image: mongo
    volumes:
      - ./protected_db/howlround-mongodb:/data/db
    command:
      - --storageEngine=mmapv1