version: "3"
services:
  web:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "3030:3030"
    stdin_open: true
    tty: true
  # mongo:
  #   image: mongo
  #   ports:
  #     - "27017:27017"
